### ISSUE TITLE
srcファイル

### ISSUE THREAD

**Issue by tokage531** [rain318/PMMP#3]
日本語にしたいのですが
クッラシュダンプをどうすればいいのかわかりません
教えていただきたいです

**Comment by rain318** [comment]
帰宅後確認します

**Comment by rain318** [comment]
体調不良のら…
取り敢えず、ダウンロードファイルを全てstart.cmdがあるところに入れるだけです。何も考えずに入れるのです！

PocketMine-MP.pharは消してくださいね

**Comment by rain318** [comment]
![img](http://i.gyazo.com/90e138c09dde9b036e6a5ab91d69fdaf.png)
こんな感じにすればOKです
