### ISSUE TITLE
やり方が分からない

### ISSUE THREAD

**Issue by rain318** [rain318/PMMP#3]
#1 に投稿されていたので移動
> Wikiも見たんですがやり方の2.があまりわからないので詳しく説明していただけないでしょうか。

図のような状態にしてください。
* 赤線 - このファイルを削除する
* 緑枠 - このフォルダを追加する
<img src="http://s1.gazo.cc/up/126389.png"></img>

**Comment by rain318** [comment]
失礼致しました。画像には書かれていませんが、以下のフォルダも作成しておいてください。
* **CrashDump**

以降、CrashDumpはCrashDumpフォルダの中に生成されるようになります。

**Comment by kurikun8** [comment]
おぉぉぉ!!
できました！！
ありがとうございました!!!

**Comment by tokage531** [comment]
やってみましたが
なぜかできないのですが
あとCrashDumpとは？

**Comment by rain318** [comment]
**このIssuseはアップデート管理用です。**
**質問に関しては、新しいIssuesを作ってください。**

**Comment by rain318** [comment]
@tokage531
>やってみましたが
>なぜかできないのですが
どのように出来ないのかを教えてください。
また、#4 にて受け付けます。
>あとCrashDumpとは？
クラッシュ時に、なぜクラッシュしたのかが掛かれているtxtファイルです。
ソフトによっては、logファイルが生成される場合もあります。
